name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Run lint
      run: yarn run lint
      env:
        CI: true

    - name: Run tests
      run: yarn run test
      env:
        CI: true

    - name: Run lint
      run: npm run lint
      env:
        CI: true

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build project
      run: npm run build

    - name: Upload production-ready build
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: build
