 deploy:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on push to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Deploying to Render..."
          curl -X POST https://api.render.com/deploy/some-service-id \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
